branches:
  only:
    - master
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.0"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
notifications:
  email:
    - dejan@golja.org

